### PR TITLE
Disk stats, refactoring and renames

### PR DESCRIPTION
**Pull request by thijsc**
Pretty big airplane pull. I implemented disk stats in a slightly nicer way than some of the other probes. I've then refactored the other ones to bring them in line with this structure.

### CODE REVIEW

**Comment by thijsc** [comment]
I've opensourced the repo and added Travis configuration. Trying to get a green build in this pull.

**Comment by thijsc** [comment]
There is something wonky going on with the values returned by process memory metrics. I think maybe Docker related? Will look into it. In the mean time this is ready for general review.

**Comment by timonv** [comment]
Cool! Have fun at Railsconf!

All the Measurement structs look awefully familiar, apart fromt there being singular an plural variants. Maybe it's an idea to make it a generic struct?

**Comment by thijsc** [comment]
I was trying to do that, but could not find a way where it's actually less code. Do take a stab at it if you like :-).

**Comment by thijsc** [comment]
Yay, green build

**Comment by matsimitsu** [comment]
:cake:

**Pull request merged**
